services:
  db:
    image: postgres:17
    container_name: university-db
    environment:
      POSTGRES_DB: universityportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - backend

  app:
    build: .
    container_name: university-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/universityportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
